# Generated by Django 3.2 on 2022-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='分类连接')),
                ('protocol', models.CharField(blank=True, default='https://', max_length=100, null=True, verbose_name='协议')),
                ('has_user_rule', models.BooleanField(default=True, verbose_name='是否加用户标识二级域名规则')),
                ('child_link', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='子条目连接')),
                ('show_count', models.IntegerField(default=0, verbose_name='超出展示')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '分类表',
                'verbose_name_plural': '分类表',
                'db_table': 'h_category',
            },
        ),
    ]
