# Generated by Django 3.2 on 2022-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='child_link',
            field=models.CharField(default='', max_length=100, verbose_name='子条目前置连接'),
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='连接'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_count',
            field=models.IntegerField(default=0, verbose_name='超出展示'),
        ),
    ]
