# Generated by Django 3.2 on 2022-01-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220116_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_user_rule',
            field=models.BooleanField(default=True, verbose_name='是否加用户标识二级域名规则'),
        ),
        migrations.AddField(
            model_name='category',
            name='protocol',
            field=models.CharField(default='https://', max_length=100, verbose_name='协议'),
        ),
        migrations.AlterField(
            model_name='category',
            name='child_link',
            field=models.CharField(default='', max_length=100, verbose_name='子条目连接'),
        ),
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(default='', max_length=100, verbose_name='分类连接'),
        ),
    ]
