# Generated by Django 3.2 on 2022-01-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20220116_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='子条目连接'),
        ),
        migrations.AlterField(
            model_name='category',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='分类连接'),
        ),
        migrations.AlterField(
            model_name='category',
            name='protocol',
            field=models.CharField(blank=True, default='https://', max_length=100, null=True, verbose_name='协议'),
        ),
    ]
