# Generated by Django 3.0.8 on 2023-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='指明用户是否被认为是活跃的。以反选代表未激活。', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='指明用户是否被认为是企业用户。', verbose_name='企业用户'),
        ),
    ]
