# Generated by Django 3.0.8 on 2023-10-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='remark',
            field=models.TextField(blank=True, max_length=10240, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='suggestion',
            field=models.TextField(blank=True, max_length=10240, null=True, verbose_name='建议'),
        ),
    ]
