# Generated by Django 2.1 on 2020-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEntry', '0002_auto_20200222_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentry',
            name='blood_sugar',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='血糖mmol/L'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='diastolic_pressure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='舒张压mmHg'),
        ),
        migrations.AlterField(
            model_name='userentry',
            name='systolic_pressure',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收缩压mmHg'),
        ),
    ]
