# Generated by Django 3.2 on 2021-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userEntry', '0003_auto_20200222_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentry',
            name='suggestion',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注'),
        ),
    ]
