# Generated by Django 2.1 on 2020-01-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('dicEntry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryship',
            name='category_id',
        ),
        migrations.AddField(
            model_name='entryship',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.Category', verbose_name='条目关联分类id外键'),
        ),
    ]
