# Generated by Django 2.1 on 2020-01-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicEntry', '0002_entry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='content',
            new_name='remark',
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='条目标题'),
        ),
    ]
