# Generated by Django 2.1 on 2020-01-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_auto_20200120_0313'),
        ('title', '0003_auto_20200119_1517'),
    ]

    operations = [
    ]
