# Generated by Django 2.0.6 on 2019-12-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='用户手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='用户邮箱')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('gander', models.CharField(choices=[('0', '女'), ('1', '男')], default='1', max_length=2, verbose_name='性别')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'db_table': 'H_User_Table',
            },
        ),
    ]
