# Generated by Django 2.0.6 on 2020-01-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminState',
            field=models.CharField(choices=[('1', '普通用户'), ('2', '超级管理员')], default='1', max_length=2, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='user',
            table='h_user',
        ),
    ]
